loki:
   auth_enabled: false
   image:
      registry: harbor.cloud-uat.zilliz.com.cn
      repository: infra/loki
      tag: patch-5a1e980
   schemaConfig:
     configs:
       - from: "2024-04-01"
         store: tsdb
         object_store: cos
         schema: v13
         index:
           prefix: loki_index_
           period: 24h
   ingester:
     chunk_encoding: snappy
   querier:
     # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
     max_concurrent: 4
   pattern_ingester:
     enabled: true
   limits_config:
     retention_period: 4320h
     allow_structured_metadata: true
     volume_enabled: true
     ingestion_rate_mb: 50
     ingestion_burst_size_mb: 100

   server:
      grpc_server_max_send_msg_size: 83886080
      grpc_server_max_recv_msg_size: 83886080

   storage:
      use_thanos_objstore: true
      bucketNames:
        chunks: liang
      object_store:
        type: cos
        cos:
          bucket: liang
          app_id: 1318287928
          region: ap-shanghai

   storage_config:
      use_thanos_objstore: true
      object_store:
        cos:
          bucket: liang
          app_id: 1318287928
          region: ap-shanghai
   compactor:
      delete_request_store: cos
      retention_enabled: true

   rulerConfig:
      alertmanager_url: http://alertmanager-main.monitoring:9093
      external_url: https://alertmanager.xx

serviceAccount:
  annotations:
    tke.cloud.tencent.com/audience: sts.cloud.tencent.com
    tke.cloud.tencent.com/role-arn: qcs::cam::uin/100031438174:roleName/test-index-pool
    tke.cloud.tencent.com/token-expiration: "7200"


deploymentMode: Distributed

ingester:
  replicas: 2 # To ensure data durability with replication
  zoneAwareReplication:
     enabled: false
querier:
  replicas: 1 # Improve query performance via parallelism
  maxUnavailable: 1
queryFrontend:
  replicas: 1
  maxUnavailable: 1
queryScheduler:
  replicas: 1
distributor:
  replicas: 2
  maxUnavailable: 0
compactor:
  replicas: 1
indexGateway:
  replicas: 1
  maxUnavailable: 1

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
   replicas: 0
read:
   replicas: 0
write:
   replicas: 0

singleBinary:
   replicas: 0

 # This exposes the Loki gateway so it can be written to and queried externaly
gateway:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      # -- Annotations for the gateway ingress
      annotations: 
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
      # -- Labels for the gateway ingress
      labels: {}
      # -- Hosts configuration for the gateway ingress, passed through the `tpl` function to allow templating
      hosts:
        - host: loki.tc-ap-nanjing.cloud-uat.zilliz.cn
          paths:
            - path: /
              # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
              pathType: Prefix
      # -- TLS configuration for the gateway ingress. Hosts passed through the `tpl` function to allow templating
      tls:
        - hosts:
            - loki.tc-ap-nanjing.cloud-uat.zilliz.cn

ruler:
  enabled: true
  replicas: 1

test:
  enabled: false

lokiCanary:
  enabled: false

minio:
  enabled: false